version: '3.4'
services:
  weaviate:
    container_name: "weaviate"
    restart: always
    image: semitechnologies/weaviate:1.28.2
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
      OLLAMA_API_HOST: 'host.docker.internal:11434'
      OLLAMA_API_SCHEME: 'http'
      LOG_LEVEL: 'debug'
    volumes:
      - weaviate_data:/var/lib/weaviate
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  weaviate_data:
    name: "weaviate_data"
